"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckSquare, Clock3, FileText, MessageCircle, Users } from "lucide-react";
import { loadRecords } from "@/lib/data";
import type { AnyRecord, ModuleKey } from "@/lib/types";
import { PageHeader } from "./page-header";
import { StatusChip } from "./status-chip";
import { EmptyState, LoadingState } from "./ui";

type CalendarItem = AnyRecord & { kind: string; module: ModuleKey; date: string };
export function CalendarPage() { const [items, setItems] = useState<CalendarItem[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { Promise.all([loadRecords("tasks"), loadRecords("events"), loadRecords("people"), loadRecords("content"), loadRecords("commitments")]).then(([tasks, events, people, content, commitments]) => { const all: CalendarItem[] = [...tasks.map((row) => ({ ...row, kind: "Task", module: "tasks" as ModuleKey, date: String(row.due_date ?? "") })), ...events.map((row) => ({ ...row, kind: "Event", module: "events" as ModuleKey, date: String(row.date_start ?? "") })), ...people.map((row) => ({ ...row, kind: "Follow-up", module: "people" as ModuleKey, date: String(row.next_follow_up_at ?? "") })), ...content.map((row) => ({ ...row, kind: "Content", module: "content" as ModuleKey, date: String(row.planned_date ?? "") })), ...commitments.map((row) => ({ ...row, kind: "Commitment", module: "commitments" as ModuleKey, date: String(row.due_date ?? "") }))].filter((item) => item.date); setItems(all.sort((a, b) => a.date.localeCompare(b.date))); }).finally(() => setLoading(false)); }, []); const grouped = useMemo(() => items.reduce<Record<string, CalendarItem[]>>((acc, item) => { const key = item.date.slice(0, 7); (acc[key] ||= []).push(item); return acc; }, {}), [items]); if (loading) return <LoadingState />; return <div><PageHeader eyebrow="All due dates" title="Calendar" description="Здесь собраны задачи, события, follow-up, commitments и даты публикаций." /><div className="mb-5 flex flex-wrap gap-2"><span className="chip"><CheckSquare size={13} /> Tasks</span><span className="chip"><CalendarDays size={13} /> Events</span><span className="chip"><Users size={13} /> People</span><span className="chip"><FileText size={13} /> Content</span><span className="chip"><MessageCircle size={13} /> Commitments</span></div>{items.length ? <div className="space-y-6">{Object.entries(grouped).map(([month, monthItems]) => <section key={month}><div className="mb-3 text-sm font-semibold text-[#74747C]">{formatMonth(month)}</div><div className="surface divide-y divide-bcc-border overflow-hidden">{monthItems.map((item) => <Link key={`${item.module}-${item.id}`} href={`/${item.module}/${item.id}`} className="flex items-center gap-4 p-4 transition hover:bg-bcc-soft/60"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bcc-lilac text-bcc-deep"><Clock3 size={17} /></span><span className="min-w-0 flex-1"><span className="block truncate font-medium">{String(item.title ?? item.name ?? `${item.first_name ?? ""} ${item.last_name ?? ""}`)}</span><span className="mt-1 block text-xs text-[#74747C]">{item.kind} · {formatDate(item.date)}</span></span><StatusChip value={item.status} /></Link>)}</div></section>)}</div> : <EmptyState title="Календарь пуст" description="Добавь сроки, события или follow-up — они появятся здесь." />}</div>; }
function formatMonth(value: string) { const date = new Date(`${value}-01T00:00:00`); return new Intl.DateTimeFormat("ru-RU", { month: "long", year: "numeric" }).format(date); }
function formatDate(value: string) { const date = new Date(`${value}T00:00:00`); return new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long" }).format(date); }
