"use client";

import Link from "next/link";
import { useEffect, useMemo } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CheckSquare, Clock3, FileText, MessageCircle, Users } from "lucide-react";
import { loadAllRecords } from "@/lib/data";
import { formatDateRu } from "@/lib/i18n";
import type { AnyRecord, ModuleKey } from "@/lib/types";
import { PageHeader } from "./page-header";
import { StatusChip } from "./status-chip";
import { EmptyState, ErrorState, LoadingState } from "./ui";

type CalendarItem = AnyRecord & { kind: string; module: ModuleKey; date: string };
const calendarSources: Array<[ModuleKey, string, string]> = [["tasks", "Задача", "due_date"], ["events", "Событие", "date_start"], ["people", "Контакт", "next_follow_up_at"], ["content", "Материал", "planned_date"], ["commitments", "Договорённость", "due_date"]];
export function CalendarPage() { const queryClient = useQueryClient(); const query = useQuery({ queryKey: ["calendar"], queryFn: async () => { const rows = await Promise.all(calendarSources.map(async ([module, kind, field]) => ({ module, kind, field, rows: await loadAllRecords(module) }))); return rows.flatMap(({ module, kind, field, rows }) => rows.map((row) => ({ ...row, kind, module, date: String(row[field] ?? "") } as CalendarItem))).filter((item) => item.date).sort((a, b) => a.date.localeCompare(b.date)); }, staleTime: 60_000 }); useEffect(() => { const onChange = () => void queryClient.invalidateQueries({ queryKey: ["calendar"] }); window.addEventListener("bcc:data-changed", onChange); return () => window.removeEventListener("bcc:data-changed", onChange); }, [queryClient]); const items = query.data ?? []; const grouped = useMemo(() => items.reduce<Record<string, CalendarItem[]>>((acc, item) => { const key = item.date.slice(0, 7); (acc[key] ||= []).push(item); return acc; }, {}), [items]); if (query.isPending) return <LoadingState label="Собираем даты…" />; if (query.isError) return <ErrorState message="Не удалось загрузить календарь." onRetry={() => void query.refetch()} />; return <div><PageHeader eyebrow="Все рабочие даты" title="Календарь" description="Задачи, события, follow-up, договорённости и даты публикаций — в одном списке." /><div className="mb-5 flex flex-wrap gap-2"><span className="chip"><CheckSquare size={13} /> Задачи</span><span className="chip"><CalendarDays size={13} /> События</span><span className="chip"><Users size={13} /> Люди</span><span className="chip"><FileText size={13} /> Материалы</span><span className="chip"><MessageCircle size={13} /> Договорённости</span></div>{items.length ? <div className="space-y-6">{Object.entries(grouped).map(([month, monthItems]) => <section key={month}><div className="mb-3 text-sm font-semibold capitalize text-[#74747C]">{formatMonth(month)}</div><div className="surface divide-y divide-bcc-border overflow-hidden">{monthItems.map((item) => <Link key={`${item.module}-${item.id}`} href={`/${item.module}/${item.id}`} className="flex items-center gap-4 p-4 transition hover:bg-bcc-soft/60"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-bcc-lilac text-bcc-deep"><Clock3 size={17} /></span><span className="min-w-0 flex-1"><span className="block truncate font-medium">{String(item.title ?? item.name ?? `${item.first_name ?? ""} ${item.last_name ?? ""}`)}</span><span className="mt-1 block text-xs text-[#74747C]">{item.kind} · {formatDateRu(item.date, { day: "numeric", month: "long" })}</span></span><StatusChip value={item.status} /></Link>)}</div></section>)}</div> : <EmptyState title="Календарь пуст" description="Добавь срок, событие или follow-up — они появятся здесь." />}</div>; }
function formatMonth(value: string) { const date = new Date(`${value}-01T00:00:00`); return new Intl.DateTimeFormat("ru-RU", { month: "long", year: "numeric" }).format(date); }
