"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Archive, ArrowLeft, CalendarClock, CheckCircle2, Edit3, ExternalLink, Link2, Plus, Save, Sparkles, UserRound } from "lucide-react";
import { addAmbassadorContribution, addWorkLog, archiveRecord, loadActivity, loadRecord, loadRecords, updateRecord } from "@/lib/data";
import { fieldLabel, formatDateRu, localizeOptions, moduleCopy, ru } from "@/lib/i18n";
import { calculateProjectHealth } from "@/lib/health";
import { displayName, getModule, type AnyRecord, type FieldConfig, type ModuleKey } from "@/lib/types";
import { PageHeader } from "./page-header";
import { StatusChip } from "./status-chip";
import { Button, EmptyState, ErrorState, Field, Input, LoadingState, Modal, Select, Textarea } from "./ui";

export function DetailPage({ module, id }: { module: ModuleKey; id: string }) {
  const router = useRouter();
  const config = getModule(module)!;
  const copy = moduleCopy(module);
  const [record, setRecord] = useState<AnyRecord | null>(null);
  const [activity, setActivity] = useState<AnyRecord[]>([]);
  const [health, setHealth] = useState<{ score: number; state: string; reasons: string[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [editOpen, setEditOpen] = useState(false);
  const [archiveOpen, setArchiveOpen] = useState(false);
  const [relationOpen, setRelationOpen] = useState(false);
  const [workLogOpen, setWorkLogOpen] = useState(false);

  async function refresh() {
    setLoading(true); setError("");
    try {
      const [next, log] = await Promise.all([loadRecord(module, id), loadActivity(module, id)]);
      setRecord(next); setActivity(log);
      if (next && module === "projects") {
        const [tasks, commitments] = await Promise.all([loadRecords("tasks", { pageSize: 100 }), loadRecords("commitments", { pageSize: 100 })]);
        setHealth(calculateProjectHealth(next, tasks, commitments));
      }
    } catch (err) { setError(err instanceof Error ? err.message : "Не удалось открыть запись."); } finally { setLoading(false); }
  }
  useEffect(() => { void refresh(); }, [module, id]);
  if (loading) return <LoadingState />;
  if (error) return <ErrorState message={error} onRetry={refresh} />;
  if (!record) return <EmptyState title="Запись не найдена" description="Возможно, она архивирована или ссылка устарела." action={<Link href={`/${module}`} className="button-secondary">Вернуться к списку</Link>} />;
  const details = config.fields.filter((field) => record[field.key] !== undefined && record[field.key] !== null && record[field.key] !== "");
  return <div>
    <Link href={`/${module}`} className="mb-5 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-[#74747C] hover:text-bcc-deep"><ArrowLeft size={16} />Назад к {copy.label.toLowerCase()}</Link>
    <PageHeader eyebrow={copy.singular} title={displayName(record)} description={String(record.description ?? record.notes ?? record.summary ?? record.situation ?? "Рабочая запись и её контекст.")} action={{ label: "Редактировать", onClick: () => setEditOpen(true) }} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-6">
      <section className="surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex flex-wrap items-center gap-2"><StatusChip value={record.status ?? record.ring ?? record.change_state ?? record.relationship_state} /><StatusChip value={record.priority} tone="brand" />{record.direction && <span className="chip">{ru(record.direction)}</span>}{record.due_date && <span className="chip"><CalendarClock size={13} />{formatDateRu(record.due_date)}</span>}</div><div className="flex gap-1"><Button variant="ghost" onClick={() => setRelationOpen(true)}><Link2 size={16} />Связать</Button><Button variant="ghost" onClick={() => setArchiveOpen(true)}><Archive size={16} />Архив</Button></div></div>{health && <HealthPanel details={health} />}{module === "tech-radar" && <RadarPanel record={record} />}{module === "events" && <EventReadiness record={record} />}{module === "people" && <RelationshipPanel record={record} />}{module === "ambassadors" && <AmbassadorPanel record={record} onUpdate={async (xp) => { await addAmbassadorContribution(id, { type: "Manual contribution", base_xp: xp, final_xp: xp, status: "Approved" }); await refresh(); }} />}</section>
      {module === "tasks" && <WorkLogSection activity={activity} onAdd={() => setWorkLogOpen(true)} />}
      <section className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">Контекст</div><h2 className="mt-1 text-xl font-semibold">Детали записи</h2></div><Button variant="ghost" onClick={() => setEditOpen(true)}><Edit3 size={16} />Изменить</Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{details.length ? details.map((field) => <DetailField key={field.key} field={field} value={record[field.key]} />) : <p className="text-sm text-[#74747C]">Пока нет дополнительных полей.</p>}</div></section>
      <section className="surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">История изменений</div><h2 className="mt-1 text-xl font-semibold">История</h2></div><span className="chip">{activity.length}</span></div>{activity.length ? <div className="mt-5 space-y-4">{activity.slice(0, 12).map((item) => <div key={item.id} className="flex gap-3"><span className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-bcc-lilac text-bcc-deep"><CheckCircle2 size={14} /></span><div><div className="text-sm font-medium">{String(item.message ?? item.action)}</div><div className="mt-0.5 text-xs text-[#8A8A90]">{formatDateTime(item.created_at)}</div></div></div>)}</div> : <p className="mt-5 text-sm text-[#74747C]">История появится после изменений и связанных действий.</p>}</section>
    </div><aside className="space-y-4"><div className="surface p-5"><div className="eyebrow">Быстрый контекст</div><div className="mt-4 space-y-3"><ContextRow label="Создано" value={formatDateTime(record.created_at)} /><ContextRow label="Обновлено" value={formatDateTime(record.updated_at)} />{record.next_action && <ContextRow label="Следующий шаг" value={String(record.next_action)} accent />}{record.external_url && <a className="flex items-center gap-2 text-sm font-medium text-bcc-deep" href={String(record.external_url)} target="_blank" rel="noreferrer"><ExternalLink size={15} />Открыть внешний источник</a>}</div></div><div className="surface-muted p-5"><div className="flex items-center gap-2 text-bcc-deep"><Sparkles size={16} /><span className="text-sm font-semibold">Подсказка по правилам</span></div><p className="mt-3 text-sm leading-6 text-[#5F4A73]">{record.next_action ? `Следующий шаг: ${String(record.next_action)}` : "Добавь следующий шаг, чтобы запись не потерялась в контексте."}</p><Button variant="secondary" className="mt-4 w-full" onClick={() => setEditOpen(true)}>Добавить следующий шаг</Button></div></aside></div>
    <EditModal open={editOpen} onClose={() => setEditOpen(false)} module={module} record={record} onSaved={(updated) => { setRecord(updated); setEditOpen(false); void refresh(); }} /><RelationModal open={relationOpen} onClose={() => setRelationOpen(false)} sourceModule={module} sourceId={id} /><TaskWorkLogModal open={workLogOpen} onClose={() => setWorkLogOpen(false)} taskId={id} onSaved={() => { setWorkLogOpen(false); void refresh(); }} /><Modal open={archiveOpen} onClose={() => setArchiveOpen(false)} title="Переместить в архив?" description="Рабочая история останется доступной в архиве."><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setArchiveOpen(false)}>Отмена</Button><Button variant="primary" onClick={async () => { await archiveRecord(module, id); router.push(`/${module}`); }}>Архивировать</Button></div></Modal>
  </div>;
}

function WorkLogSection({ activity, onAdd }: { activity: AnyRecord[]; onAdd: () => void }) { const logs = activity.filter((item) => item.action === "work log added"); return <section className="surface p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><div className="eyebrow">Рабочий журнал</div><h2 className="mt-1 text-xl font-semibold">Что произошло по задаче</h2></div><Button variant="brand" onClick={onAdd}><Plus size={16} />Добавить запись</Button></div>{logs.length ? <div className="mt-5 space-y-4">{logs.map((item) => <div key={item.id} className="rounded-2xl bg-bcc-soft p-4"><div className="text-sm font-medium">{String(item.message)}</div><div className="mt-1 text-xs text-[#8A8A90]">{formatDateTime(item.created_at)}</div></div>)}</div> : <p className="mt-5 text-sm text-[#74747C]">Добавляй результат, обсуждение и следующий шаг — это сохраняет рабочую память.</p>}</section>; }
function EditModal({ open, onClose, module, record, onSaved }: { open: boolean; onClose: () => void; module: ModuleKey; record: AnyRecord; onSaved: (record: AnyRecord) => void }) { const config = getModule(module)!; const [values, setValues] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); useEffect(() => { if (open) setValues(Object.fromEntries(config.fields.map((field) => [field.key, String(record[field.key] ?? "")]))); }, [open, config, record]); async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { onSaved(await updateRecord(module, record.id, values)); } catch (err) { setError(err instanceof Error ? err.message : "Не удалось сохранить"); } finally { setSaving(false); } } return <Modal open={open} onClose={onClose} title={`Редактировать ${moduleCopy(module).singular}`} description="Изменения попадут в облачную базу и историю изменений."><form onSubmit={submit} className="space-y-4">{config.fields.map((field) => <RecordField key={field.key} field={field} value={values[field.key] ?? ""} onChange={(value) => setValues((current) => ({ ...current, [field.key]: value }))} />)}{error && <p className="rounded-xl bg-[#FDECEC] px-3 py-2 text-sm text-[#AF3030]" role="alert">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Отмена</Button><Button type="submit" variant="brand" disabled={saving}><Save size={16} />{saving ? "Сохраняем…" : "Сохранить"}</Button></div></form></Modal>; }
function TaskWorkLogModal({ open, onClose, taskId, onSaved }: { open: boolean; onClose: () => void; taskId: string; onSaved: () => void }) { const [values, setValues] = useState({ done: "", people: "", discussed: "", result: "", next: "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); if (!values.done.trim()) { setError("Запиши хотя бы результат действия."); return; } setSaving(true); try { await addWorkLog(taskId, values); setValues({ done: "", people: "", discussed: "", result: "", next: "" }); onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "Не удалось сохранить запись"); } finally { setSaving(false); } } return <Modal open={open} onClose={onClose} title="Рабочий журнал" description="Короткая запись о том, что произошло."><form onSubmit={submit} className="space-y-4"><Field label="Что сделал?" hint="Обязательное поле"><Textarea required value={values.done} onChange={(event) => setValues({ ...values, done: event.target.value })} /></Field><Field label="С кем взаимодействовал?"><Input value={values.people} onChange={(event) => setValues({ ...values, people: event.target.value })} /></Field><Field label="Что обсудили?"><Textarea value={values.discussed} onChange={(event) => setValues({ ...values, discussed: event.target.value })} /></Field><Field label="Какой результат?"><Textarea value={values.result} onChange={(event) => setValues({ ...values, result: event.target.value })} /></Field><Field label="Что дальше?"><Input value={values.next} onChange={(event) => setValues({ ...values, next: event.target.value })} /></Field>{error && <p className="rounded-xl bg-[#FDECEC] px-3 py-2 text-sm text-[#AF3030]" role="alert">{error}</p>}<div className="flex justify-end"><Button type="submit" variant="brand" disabled={saving}>{saving ? "Сохраняем…" : "Сохранить запись"}</Button></div></form></Modal>; }
function RelationModal({ open, onClose, sourceModule, sourceId }: { open: boolean; onClose: () => void; sourceModule: ModuleKey; sourceId: string }) { const [targetModule, setTargetModule] = useState<ModuleKey>("projects"); const [targetId, setTargetId] = useState(""); const [rows, setRows] = useState<AnyRecord[]>([]); const [relation, setRelation] = useState("RELATED_TO"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { if (open) loadRecords(targetModule, { pageSize: 50 }).then(setRows).catch(() => setRows([])); }, [open, targetModule]); async function submit(event: React.FormEvent) { event.preventDefault(); if (!targetId) return; setSaving(true); try { const { addRelation } = await import("@/lib/data"); await addRelation(sourceModule, sourceId, relation, targetModule, targetId); setMessage("Связь сохранена"); setTimeout(onClose, 550); } catch (err) { setMessage(err instanceof Error ? err.message : "Не удалось сохранить связь"); } finally { setSaving(false); } } return <Modal open={open} onClose={onClose} title="Добавить связь" description="Связь будет видна в истории изменений."><form onSubmit={submit} className="space-y-4"><Field label="Тип связи"><Input value={relation} onChange={(event) => setRelation(event.target.value)} placeholder="RELATED_TO" /></Field><Field label="Сущность"><Select value={targetModule} onChange={(event) => { setTargetModule(event.target.value as ModuleKey); setTargetId(""); }}><option value="projects">Проект</option><option value="tasks">Задача</option><option value="people">Контакт</option><option value="events">Событие</option><option value="content">Материал</option><option value="documents">Документ</option><option value="knowledge">Кейс</option></Select></Field><Field label="Запись"><Select value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">Выбери запись</option>{rows.map((row) => <option key={row.id} value={row.id}>{displayName(row)}</option>)}</Select></Field>{message && <p className="rounded-xl bg-bcc-soft px-3 py-2 text-sm text-[#5F5F68]">{message}</p>}<div className="flex justify-end"><Button variant="brand" type="submit" disabled={saving || !targetId}><Link2 size={16} />{saving ? "Сохраняем…" : "Связать"}</Button></div></form></Modal>; }
function RecordField({ field, value, onChange }: { field: FieldConfig; value: string; onChange: (value: string) => void }) { return <Field label={fieldLabel(field)}>{field.type === "textarea" ? <Textarea value={value} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder} /> : field.type === "select" ? <Select value={value} onChange={(event) => onChange(event.target.value)}>{localizeOptions(field.options).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</Select> : <Input type={field.type === "date" ? "date" : field.type === "number" ? "number" : field.type === "url" ? "url" : "text"} value={value} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder} />}</Field>; }
function DetailField({ field, value }: { field: FieldConfig; value: unknown }) { return <div><div className="text-xs uppercase tracking-[0.08em] text-[#8A8A90]">{fieldLabel(field)}</div><div className="mt-1 whitespace-pre-wrap text-sm leading-6 text-bcc-ink">{field.type === "url" ? <a href={String(value)} target="_blank" rel="noreferrer" className="text-bcc-deep underline">{String(value)}</a> : field.type === "date" ? formatDateRu(value) : field.type === "select" ? ru(value) : String(value)}</div></div>; }
function ContextRow({ label, value, accent }: { label: string; value: string; accent?: boolean }) { return <div><div className="text-xs text-[#8A8A90]">{label}</div><div className={`mt-0.5 text-sm leading-5 ${accent ? "font-medium text-bcc-deep" : "text-bcc-ink"}`}>{value}</div></div>; }
function HealthPanel({ details }: { details: { score: number; state: string; reasons: string[] } }) { return <div className="mt-6 rounded-2xl bg-bcc-soft p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="eyebrow">Здоровье проекта</div><div className="mt-1 flex items-baseline gap-2"><span className="text-4xl font-semibold tracking-[-0.06em]">{details.score}</span><StatusChip value={details.state} /></div></div><div className="h-16 w-16 rounded-full p-1" style={{ background: `conic-gradient(#8934F9 ${details.score * 3.6}deg, #E8E7EC 0deg)` }}><div className="flex h-full w-full items-center justify-center rounded-full bg-bcc-soft text-xs font-semibold">{details.score}%</div></div></div><div className="mt-4 space-y-1 text-sm text-[#5F5F68]">{details.reasons.map((reason) => <div key={reason}>• {reason}</div>)}</div></div>; }
function RadarPanel({ record }: { record: AnyRecord }) { return <div className="mt-6 rounded-2xl bg-bcc-lilac/60 p-4"><div className="flex items-center gap-2 text-bcc-deep"><Sparkles size={16} /><span className="font-semibold">Рекомендация</span></div><p className="mt-2 text-sm leading-6 text-[#5F4A73]">{String(record.recommendation ?? "Добавь прозрачную рекомендацию для команды.")}</p><div className="mt-3 flex flex-wrap gap-2"><StatusChip value={record.ring} /><StatusChip value={record.change_state} /></div></div>; }
function EventReadiness({ record }: { record: AnyRecord }) { const target = Number(record.registration_target ?? 0); const registrations = Number(record.registrations ?? 0); const progress = target ? Math.min(100, Math.round((registrations / target) * 100)) : 0; return <div className="mt-6 rounded-2xl bg-bcc-cyan/50 p-4"><div className="flex items-center justify-between"><div><div className="eyebrow">Готовность события</div><div className="mt-1 text-3xl font-semibold">{progress}%</div></div><CalendarClock className="text-[#177479]" /></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/70"><div className="h-full rounded-full bg-[#177479]" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-xs text-[#3E6B6E]">{registrations} из {target || "—"} регистраций · проверь критичные задачи до дня события.</p></div>; }
function RelationshipPanel({ record }: { record: AnyRecord }) { const days = record.last_interaction_at ? Math.floor((Date.now() - new Date(String(record.last_interaction_at)).getTime()) / 86400000) : 999; const score = Math.max(0, Math.min(100, (days < 14 ? 60 : days < 30 ? 42 : 20) + (record.next_follow_up_at ? 25 : 0) + (record.relationship_type ? 15 : 0))); const state = score >= 75 ? "Active" : score >= 50 ? "Warm" : score >= 25 ? "Cooling" : "Dormant"; return <div className="mt-6 rounded-2xl bg-bcc-cyan/50 p-4"><div className="flex items-center justify-between"><div><div className="eyebrow">Активность связи</div><div className="mt-1 flex items-baseline gap-2"><span className="text-3xl font-semibold">{score}</span><StatusChip value={state} /></div></div><UserRound className="text-[#177479]" /></div><p className="mt-3 text-xs leading-5 text-[#3E6B6E]">Прозрачный показатель по давности контакта, follow-up и типу связи. Это не оценка человека.</p></div>; }
function AmbassadorPanel({ record, onUpdate }: { record: AnyRecord; onUpdate: (xp: number) => Promise<void> }) { const [open, setOpen] = useState(false); return <div className="mt-6 rounded-2xl bg-bcc-lilac/60 p-4"><div className="flex items-center justify-between"><div><div className="eyebrow">Журнал XP</div><div className="mt-1 text-3xl font-semibold">{Number(record.total_xp ?? 0)} XP</div></div><UserRound className="text-bcc-deep" /></div><div className="mt-2 text-sm text-[#5F4A73]">{ru(record.track ?? "Трек не указан")} · {ru(record.level ?? "LV.0 Newcomer")}</div><Button variant="brand" className="mt-4" onClick={() => setOpen(true)}><Plus size={16} />Начислить XP</Button><XpModal open={open} onClose={() => setOpen(false)} onSave={async (xp) => { await onUpdate(xp); setOpen(false); }} /></div>; }
function XpModal({ open, onClose, onSave }: { open: boolean; onClose: () => void; onSave: (xp: number) => Promise<void> }) { const [xp, setXp] = useState("20"); return <Modal open={open} onClose={onClose} title="Добавить вклад" description="Запись сохранится в XP-журнале как источник истины."><form onSubmit={async (event) => { event.preventDefault(); await onSave(Number(xp)); }} className="space-y-4"><Field label="XP"><Input type="number" min="1" required value={xp} onChange={(event) => setXp(event.target.value)} /></Field><p className="text-xs leading-5 text-[#74747C]">Итоговый XP подтверждает пользователь, автоматические множители не применяются.</p><div className="flex justify-end"><Button variant="brand" type="submit">Сохранить вклад</Button></div></form></Modal>; }
function formatDateTime(value: unknown) { if (!value) return "—"; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value) : new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(date); }
